### PR TITLE
chore: modify the registeruser usecase to comply with the dip principle

### PR DESCRIPTION
**Pull request by PedroMiotti**
Hey Harvic, first of all, amazing template man, really appreciate all the time you took to develop nodetskeleton, all of the *-tsk libraries are really time saving. 

Just made some tiny adjustments on the registeruser use case to comply with the dependency inversion principle, maybe a little overkill, don't know if its 100% correct or if it is even useful. 

Thanks again man.

### CODE REVIEW

**Comment by harvic3** [comment]
Hi @PedroMiotti, first of all, thank you very much for your interest in this hobby project and thank you for taking the time and the intention to contribute to improve this project.

As for your proposal, I like it, it is a very good practice to decouple the core of an application from external libraries and packages, especially if these dependencies implement some communication protocol behind the scenes, however there are certain dependencies (packages and libraries) in which the inversion of control through the architecture of ports and adapters is not a good practice or at least it is not the best way to do it because you could have many contracts injected to a use case unit and this would make it impractical and in the long term it could become complicated to manage these dependencies without mentioning the amount of mocks that you would have to implement in the tests, and more if they are libraries and packages of code units that compute bytes without the consumption of external services that imply the use of some communication protocol.

Therefore for the intention you have in my humble opinion I would recommend the use of a less traumatic abstraction pattern that brings practicality, agility, mental health, less complexity and better handling of those contracts, that ideal pattern in this particular case, would be the facade pattern.

**Why the facade pattern and not an adapter?**

1. It fulfills the purpose of decoupling by not having a dependency scattered all over your application layer and adapters.
2. It brings agility to the development of your tests without the need to implement a large number of mocks.
3. You can handle it in your application layer as part of the shared utilities as a concrete entity that implements an interface (your contract) and, obviously, our capital sin, that library or package that does the heavy lifting for us.
4. If tomorrow you need to change that package or library, you only need to touch one unit of code, and the same if it were an adapter, however the management of the latter becomes more complicated in the long run for the reasons I have already explained.

Finally, when I have to make a decision like this, I check if my dependency uses or not the consumption of external services, different from the language's own APIs such as access to services of the computing machine such as Date and Time, Telemetry, processes, among other resources provided naturally by the language.

What do you think about it? 
_Remember that "the sophisticated is the enemy of the simple"._

I look forward to your comments because I learn every day.

Greetings!

**Comment by PedroMiotti** [comment]
It makes total sense !!! Thanks for taking the time to explain, learned so much just by reading your comment.

When you say, to use the facade pattern, you mean a facade class that imports all the external dependencies ? 
For example : 

```
import { DateTime } from "luxon";
import { v4 } from "uuid";

export class DependencyFacade implements IProvider{
  getDateNow(): string {
    return DateTime.local().toISO();
  }

  generateUUID(): string {
    return v4();
  }
}
```
... something like this ??

And also, if its not to much to ask (please don't feel obligated to respond, i know it will take some time). I have been having trouble on how to handle database errors (like ``` Error: ER_NO_SUCH_TABLE: Table 'ownstoretest.usercd' doesn't exist ``` for example ),  i would like to handle the error on the adapter/provider layer, this is what i am currently doing : 

```
login(user: UserLoginDto): Promise<User> {
  return UserModel.login(user)
    .then((user) => {
      return user
    }).catch((e) => {
      throw new ApplicationError(
          e.message,
          e.code || applicationStatus.INTERNAL_ERROR,
          JSON.stringify(e),
      );
  });
}
```
if there is an error, the model rejects the promise. When i throw the applicationError shouldn't pass to the error handling middleware ? Instead it continues to the usecase (don't feel like it would be the best practice to handle a database like error on the application layer). 

Appreciate all the help @harvic3,  and again please don´t fell obligated to respond, i know i already abused  😀    .

Looking forward to hearing from you, have a good one !

**Comment by harvic3** [comment]
Hi @PedroMiotti, when I mentioned a facade pattern I meant something like this, because we can't mix things up, remember the single responsibility principle (SRP). 

Now why with a contract?, because you can't use that unit of code inside the domain layer directly, you must inject it by constructor or by method based on your domain contract (utilityContracts), but in the application layer or adapters layer there is no problem to use it directly.

image

I will upload the two examples (DateTimeUtils and GuidUtils) in the next commit in case you want to review the implementation and make your contributions and improvements if necessary.

Regarding the error handling of the adapter layer (providers and repositories, even the application layer) you must take into account that a common and wild user does not care about a message of the type you mention in the example, the user is interested in a message like "Oh sorry, something went wrong" even mentioning the action that the user was trying to execute, and the error must be sent somehow to a centralized error log, either a repository or a system like Sentry or Loggly to handle that technical information internally.

Now, a Throw is an action that cuts the flow of a request when it is launched and this will end up in the error handler of your application, so if you want to avoid this, then you must give a different handling to the error control in the flow of a request, for example you can do the following:

```ts
  // Adapter unit
  async login(user: UserLoginDto): Promise<User> {
    return UserModel.login(user)
      .then((user) => {
        return user;
      })
      .catch((error) => {
        Promise.resolve(logProvider.log("Error message", error));
        return Promise.reject(
          this.resources.get(this.resourceKeys.INVALID_USER_OR_PASSWORD),
          this.applicationStatusCode.INTERNAL_ERROR,
        );
      });
  }
  ```
  
And in the Application layer, into execute method of your useCase something like: 

```ts
// Into execute method of your useCase
    const user = await this.authProvider.login(loginDto).catch((err) => {
      console.log("Do something with this error, for example send a Log centralized system", err);
      return null;
    });
    if (!user) {
      result.setError(
        this.resources.get(this.resourceKeys.SOMETHING_WENT_WRONG),
        this.applicationStatus.INTERNAL_ERROR,
      );
      // Manage error through of a Throw or return result
      // In this case the error will be handled by the error handler
      this.handleResultError(result);
      // In this case the error will be handled by the response strategy
      return result;
    }
    result.setData(message, this.applicationStatus.SUCCESS);
    return result;
   ```
   
Let me know if this resolves your concerns.

Greetings!!!

**Comment by PedroMiotti** [comment]
Hey @harvic3, very nice solution, its much cleaner than what i did before.

Regarding the error handling, you are completely right, the user does not care about the database error. Created a logger and now the flow of the application its much better. 

Thank you very much for all your help, and the work you put into this project.

Have a nice one !!

**Pull request closed without merging**
